[package]
name = "url_short"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http_serv = { git = "https://github.com/GamingGuy003/http_serv.git", branch = "main" }
